### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by shakith** [MarianoJT88/PD-Flow#1]
Hi Mariano,

I am trying to use your real-time PD flow with Kinect and OpenNI to see the algorithm. Left side of the screen shot attached shows the error when trying to run Scene-Flow-Visualization. Right side of the screen shot attached shows the output when running the NIViwer. The NIViwer runs successfully with the Kinect. It seems Scene-Flow-Visualization causes a segmentation error at write_register: 0x0005 <= 0x01.
![screenshot](https://cloud.githubusercontent.com/assets/2685014/13348956/ffc7ef18-dc76-11e5-8b66-6d5a51de6c2a.png)

Which version of the driver and openni are you using?
I am using the version from here https://github.com/OpenKinect/libfreenect and here https://github.com/occipital/openni2.

Any suggestions on where to debug this from?

Best regards,
Shakith

**Comment by MarianoJT88** [comment]
Hi Shakith,
In principle my code is not prepared to work directly with the Kinect sensor. It works with OpenNI2 and Primesense/Asus cameras. However, it should be pretty easy to make it work with Kinect if OpenNI2 has support for it. You should modify the methods "OpenCamera", "CloseCamera" and "CaptureFrame" within the scene_flow_visualization.cpp file so that they use the right functions/procedure to open the Kinect sensor. If you have been working with the Kinect sensor then I can imagine that you know how to handle the camera, otherwise you could try to copy it from the NIViewer example.
I hope this helps,Best Regards,Mariano

Date: Fri, 26 Feb 2016 01:58:52 -0800

**Comment by shakith** [comment]
Thanks. Managed to get the camera working with it with minor code changes.
However, I do not see any motion fields with any body motion or any rigid body motions even with small row number. The only place any motion fields become visible is when you move the camera while looking at the ceiling. Maybe the registration is incorrect from Kinect. Any suggestions on 
this?

**Comment by MarianoJT88** [comment]
That is super strange, you should see a vector (blue line) associated to every point that the camera observes (so thousands of them). Do you see the point clouds properly or you cannot see that either? Could you send me a picture of what you see?

Date: Fri, 26 Feb 2016 06:20:07 -0800

**Comment by shakith** [comment]
![body1](https://cloud.githubusercontent.com/assets/2685014/13355292/ea0642aa-dc9f-11e5-9380-dc446c02e5df.png)
![ceiling](https://cloud.githubusercontent.com/assets/2685014/13355293/ea1b512c-dc9f-11e5-8530-344a754d8362.png)
The pointcloud is quite visible. Here are the two screenshots. The one with motion fields is the one looking at the ceiling. The other one is with body motion, however without motion fields.

**Comment by MarianoJT88** [comment]
They seem to be misaligned. I would dare to say that those lines are actually the motion that it is "trying" to estimate for the head, but it is of course not at the right place...Check if everything is fine/consistent with the variables "cam_mode", "rows", "cols" and "ctf_levels" (which means coarse-to-fine levels). For example, if cam_mode ==1, my code will expect the camera images to be 480x640 whereas if cam_mode ==2 then it will expect to receive images at a resolution of 240x320.

Mariano

Date: Fri, 26 Feb 2016 06:46:40 -0800

**Comment by shakith** [comment]
Found the issue, I copied the commented value //2.f/sqrtf(dxu_dxu + dzu_dzu); directly to replace rhypotf. It should have been 2.f/sqrtf(dxu_2_dxu_2 + dzu_2_dzu_2).  Both line 767 and 772 in  https://github.com/MarianoJT88/PD-Flow/blob/master/pdflow_cudalib.cu
Thanks for the help. It is able to track the motion field now.

**Comment by MarianoJT88** [comment]
Good, I am happy to hear that!

Date: Fri, 26 Feb 2016 07:52:55 -0800
