### ISSUE TITLE
Potential GPU memory leak

### ISSUE THREAD

**Issue by ChrGri** [MarianoJT88/PD-Flow#7]
After running the code for a while, I noticed that the GPU memory consumptions increases over time, until the estimated RGB-D flow vanishes.

Adding
"
__host__ void CSF_cuda::freeDeviceMemory()
{
...
cudaFree(colour_wf_dev);
cudaFree(depth_wf_dev);
}
"
to "pdflow_cudalib.cu" solved it for me.

**Comment by MarianoJT88** [comment]
Thanks for reporting this. Could you commit that change? I will accept the change.

**Comment by MarianoJT88** [comment]
It should be fixed now, I close the issue.
